
export default {
    controller: Symbol("controller"),
    animController: Symbol("animController"),
    signupUiStore: Symbol("signupUiStore"),
    loginUIStore: Symbol("loginUIStore"),
    resetPasswordFromEmailController: Symbol("resetPasswordFromEmailController"),
    settingsConsultationController: Symbol("settingsConsultationController"),
    accountController: Symbol("accountController"),
    reviewsController: Symbol("reviewsController"),
    doctorSettingsController: Symbol("doctorSettingsController"),
    notificationsController: Symbol("notificationsController"),
    linkController: Symbol("linkController"),
    passwordController: Symbol("passwordController"),
    supportController: Symbol("supportController"),
    detailDoctorController: Symbol("detailDoctorController"),
    findDoctorController: Symbol("findDoctorController"),
    symptomsController: Symbol("symptomsController"),
    symptomsSliderController: Symbol("symptomsSliderController"),
    appointController: Symbol("appointController"),
    consultationController: Symbol("consultationController"),
    balanceController: Symbol("balanceController"),
    userHubController: Symbol("userHubController"),
}
